#!/usr/bin/env python3
"""Refresh the AUTO block of `_shared/sanctum-bridge.md` from the live bridge.

Reads CF Access service-token credentials and a SharePoint HMAC secret from
either env vars or the macOS keychain, fetches `/_manifest` from
`bridge.nepveu.name`, and rewrites the section between
``<!-- AUTO -->`` and ``<!-- /AUTO -->`` of the helper file.

Idempotent: a re-run with no manifest change leaves the file byte-identical
(the embedded comment uses the manifest's content hash, not a wall-clock
timestamp). Safe to wire into a cron / launchd timer.

Exit codes:
  0 — file is up to date (with or without writing)
  1 — error fetching or parsing the manifest
  2 — `--check` set and the file would change
"""
from __future__ import annotations

import argparse
import hashlib
import hmac
import json
import os
import re
import subprocess
import sys
import urllib.error
import urllib.request
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

DEFAULT_BRIDGE_URL = "https://bridge.nepveu.name"
DEFAULT_HELPER_PATH = (
    Path(__file__).resolve().parents[1] / "_shared" / "sanctum-bridge.md"
)
AUTO_OPEN = "<!-- AUTO -->"
AUTO_CLOSE = "<!-- /AUTO -->"
# Line-anchored markers, so a stray ``<!-- AUTO -->`` reference inside the
# prose (e.g. in narrative copy that documents the markers themselves) does
# not get matched.
_OPEN_RE = re.compile(r"^<!-- AUTO -->$", re.MULTILINE)
_CLOSE_RE = re.compile(r"^<!-- /AUTO -->$", re.MULTILINE)


# --------------------------------------------------------------------------- #
# Secret loading
# --------------------------------------------------------------------------- #

def _from_keychain(service: str) -> str | None:
    try:
        out = subprocess.check_output(
            ["security", "find-generic-password", "-s", service, "-w"],
            stderr=subprocess.DEVNULL,
        )
        return out.decode().strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None


def _resolve(*, env_name: str, keychain_service: str) -> str:
    val = os.environ.get(env_name) or _from_keychain(keychain_service)
    if not val:
        sys.stderr.write(
            f"missing credential: set ${env_name} or keychain entry "
            f"'{keychain_service}'\n"
        )
        sys.exit(1)
    return val


# --------------------------------------------------------------------------- #
# Manifest fetch
# --------------------------------------------------------------------------- #

def fetch_manifest(base: str) -> dict[str, Any]:
    cf_id = _resolve(
        env_name="CF_ACCESS_ID",
        keychain_service="sanctum-bridge-cf-access-client-id",
    )
    cf_secret = _resolve(
        env_name="CF_ACCESS_SECRET",
        keychain_service="sanctum-bridge-cf-access-client-secret",
    )
    hmac_secret = _resolve(
        env_name="SHAREPOINT_HMAC_SECRET",
        keychain_service="sanctum-bridge-hmac-sharepoint",
    )

    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    nonce = str(uuid.uuid4())
    body = b""
    canonical = f"{ts}\n{nonce}\nGET\n/_manifest\n{hashlib.sha256(body).hexdigest()}"
    sig = hmac.new(
        hmac_secret.encode(), canonical.encode(), hashlib.sha256
    ).hexdigest()

    req = urllib.request.Request(
        f"{base}/_manifest",
        method="GET",
        headers={
            # Cloudflare's bot-management trips on the default
            # ``Python-urllib/X.Y`` UA (error 1010). A real string clears it.
            "User-Agent": "sanctum-bridge-skill-sync/0.1",
            "CF-Access-Client-Id": cf_id,
            "CF-Access-Client-Secret": cf_secret,
            "Authorization": "SanctumHMAC v1",
            "X-Sanctum-Module": "sharepoint",
            "X-Sanctum-Timestamp": ts,
            "X-Sanctum-Nonce": nonce,
            "X-Sanctum-Signature": sig,
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            return json.load(resp)
    except urllib.error.HTTPError as exc:
        sys.stderr.write(f"manifest fetch failed: HTTP {exc.code}\n")
        sys.stderr.write(exc.read().decode("utf-8", errors="replace") + "\n")
        sys.exit(1)
    except urllib.error.URLError as exc:
        sys.stderr.write(f"manifest fetch failed: {exc}\n")
        sys.exit(1)


# --------------------------------------------------------------------------- #
# Markdown rendering
# --------------------------------------------------------------------------- #

def render_auto_block(manifest: dict[str, Any]) -> str:
    payload = json.dumps(manifest, sort_keys=True).encode()
    digest = hashlib.sha256(payload).hexdigest()[:16]

    lines = [
        AUTO_OPEN,
        f"<!-- regenerated by scripts/sync-bridge-manifest.py — manifest sha256={digest} -->",
        "",
        "## Available bridge modules",
        "",
    ]
    for mod in manifest.get("modules", []):
        lines.append(f"### `{mod['name']}` (v{mod['version']})")
        lines.append("")
        for action in mod.get("actions", []):
            lines.append(f"#### `{mod['name']}.{action['name']}`")
            lines.append("")
            if action.get("summary"):
                lines.append(action["summary"])
                lines.append("")
            lines.append(f"- HTTP: `{action['method']} /{mod['name']}{action['path']}`")
            lines.append(f"- MCP tool: `{mod['name']}.{action['name']}`")
            lines.append("")
            if action.get("request_schema"):
                lines.append("**Request body**")
                lines.append("")
                lines.append("```json")
                lines.append(json.dumps(action["request_schema"], indent=2))
                lines.append("```")
                lines.append("")
            if action.get("response_schema"):
                lines.append("**Response**")
                lines.append("")
                lines.append("```json")
                lines.append(json.dumps(action["response_schema"], indent=2))
                lines.append("```")
                lines.append("")
    lines.append(AUTO_CLOSE)
    return "\n".join(lines)


def replace_auto_block(text: str, new_block: str) -> str:
    open_m = _OPEN_RE.search(text)
    close_m = _CLOSE_RE.search(text, open_m.end()) if open_m else None
    if not open_m or not close_m:
        sys.stderr.write(
            f"helper missing AUTO markers (must be on their own lines): "
            f"{AUTO_OPEN!r} ... {AUTO_CLOSE!r}\n"
        )
        sys.exit(1)
    return text[: open_m.start()] + new_block + text[close_m.end():]


# --------------------------------------------------------------------------- #
# Main
# --------------------------------------------------------------------------- #

def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--bridge-url", default=DEFAULT_BRIDGE_URL)
    p.add_argument("--helper", type=Path, default=DEFAULT_HELPER_PATH)
    p.add_argument(
        "--check",
        action="store_true",
        help="exit 2 if the file would change; do not write",
    )
    args = p.parse_args(argv)

    if not args.helper.exists():
        sys.stderr.write(f"helper not found: {args.helper}\n")
        return 1

    manifest = fetch_manifest(args.bridge_url.rstrip("/"))
    new_block = render_auto_block(manifest)

    current = args.helper.read_text(encoding="utf-8")
    updated = replace_auto_block(current, new_block)

    if updated == current:
        print("no change")
        return 0

    if args.check:
        sys.stderr.write("would change — re-run without --check to write\n")
        return 2

    args.helper.write_text(updated, encoding="utf-8")
    delta = sum(1 for a, b in zip(updated, current) if a != b)
    print(f"updated {args.helper} (~{delta} chars changed)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
